shell = "zsh"
[plugins]

[plugins.v]
github = "jeffreytse/zsh-vi-mode"

[plugins.cp]
github = "zsh-users/zsh-completions"

[plugins.as]
github = "zsh-users/zsh-autosuggestions"

[plugins.sh]
github = "zsh-users/zsh-syntax-highlighting"

[plugins.hss]
github = "zsh-users/zsh-history-substring-search"

[plugins.lfcd]
gist = "2405ee9326a4901e9fe6ba66b1cca476"

[plugins.vicursor]
gist = "cfadf605824e42d50d5212967300a2ed"
