# all those glyphs will show as weird squares if you don't have the correct patched font
# My advice is to use NerdFonts which can be found here:
# https://github.com/ryanoasis/nerd-fonts
# Default fallback icons
[defaults]
file = "ğŸ“ƒ"
directory = "ğŸ“"
# File extension match
[ext]
"bin" = "âš™ï¸ "
"exe" = "âš™ï¸ "
"config" = "ğŸ“„"
"conf" = "ğŸ“„"
"txt" = "ğŸ“„"
"ini" = "ğŸ“„"
"log" = "ğŸ“„"
"rc" = "ğŸ“„"
"rules" = "ğŸ“„"
"json" = "ğŸ“„"
"example" = "ğŸ“„"
"tex" = "ğŸ“œ"
"md" = "ğŸ“"
"README" = "ğŸ“"
"r" = "ğŸ“‰"
"R" = "ğŸ“‰"
"rmd" = "ğŸ“‰"
"Rmd" = "ğŸ“‰"
"nfo" = "â„¹ "
"info" = "â„¹ "
"md5" = "ğŸ”"
"crt" = "ğŸ”"
"urls" = "ğŸŒ"
"html" = "ğŸŒ"
"xml" = "ğŸŒ"
"css" = "ğŸ¨"
"pdf" = "ğŸ‡µ "
"djvu" = "ğŸ“–"
"epub" = "ğŸ“–"
"azw3" = "ğŸ“–"
"mobi" = "ğŸ“–"
"zim" = "ğŸ““"
"csv" = "ğŸ“Š"
"xls" = "ğŸ“Š"
"xlsx" = "ğŸ“Š"
"doc" = "ğŸ‡¼ "
"docx" = "ğŸ‡¼ "
"wps" = "ğŸ‡¼ "
"iso" = "ğŸ“€"
"img" = "ğŸ“€"
"part" = "ğŸ§©"
"jar" = "â™¨ï¸ "
"java" = "â™¨ï¸ "
"torrent" = "ğŸ”½"
"tar" = "ğŸ“¥"
"tgz" = "ğŸ“¥"
"arc" = "ğŸ“¥"
"arj" = "ğŸ“¥"
"taz" = "ğŸ“¥"
"lha" = "ğŸ“¥"
"lz4" = "ğŸ“¥"
"lzh" = "ğŸ“¥"
"lzma" = "ğŸ“¥"
"tlz" = "ğŸ“¥"
"txz" = "ğŸ“¥"
"tzo" = "ğŸ“¥"
"t7z" = "ğŸ“¥"
"zip" = "ğŸ“¥"
"z" = "ğŸ“¥"
"dz" = "ğŸ“¥"
"gz" = "ğŸ“¥"
"lrz" = "ğŸ“¥"
"lz" = "ğŸ“¥"
"lzo" = "ğŸ“¥"
"xz" = "ğŸ“¥"
"zst" = "ğŸ“¥"
"tzst" = "ğŸ“¥"
"bz2" = "ğŸ“¥"
"bz" = "ğŸ“¥"
"tbz" = "ğŸ“¥"
"tbz2" = "ğŸ“¥"
"tz" = "ğŸ“¥"
"deb" = "ğŸ“¥"
"rpm" = "ğŸ“¥"
"war" = "ğŸ“¥"
"ear" = "ğŸ“¥"
"sar" = "ğŸ“¥"
"rar" = "ğŸ“¥"
"alz" = "ğŸ“¥"
"ace" = "ğŸ“¥"
"zoo" = "ğŸ“¥"
"cpio" = "ğŸ“¥"
"7z" = "ğŸ“¥"
"rz" = "ğŸ“¥"
"cab" = "ğŸ“¥"
"wim" = "ğŸ“¥"
"swm" = "ğŸ“¥"
"dwm" = "ğŸ“¥"
"esd" = "ğŸ“¥"
"jpg" = "ğŸŒ"
"jpeg" = "ğŸŒ"
"mjpg" = "ğŸŒ"
"mjpeg" = "ğŸŒ"
"gif" = "ğŸŒ"
"bmp" = "ğŸŒ"
"pbm" = "ğŸŒ"
"pgm" = "ğŸŒ"
"ppm" = "ğŸŒ"
"tga" = "ğŸŒ"
"xbm" = "ğŸŒ"
"xpm" = "ğŸŒ"
"tif" = "ğŸŒ"
"tiff" = "ğŸŒ"
"png" = "ğŸŒ"
"svg" = "ğŸŒ"
"svgz" = "ğŸŒ"
"mng" = "ğŸŒ"
"pcx" = "ğŸŒ"
"mov" = "ğŸŒ"
"mpg" = "ğŸŒ"
"mpeg" = "ğŸŒ"
"m2v" = "ğŸŒ"
"webm" = "ğŸŒ"
"ogm" = "ğŸŒ"
"m4v" = "ğŸŒ"
"mp4v" = "ğŸŒ"
"vob" = "ğŸŒ"
"qt" = "ğŸŒ"
"nuv" = "ğŸŒ"
"wmv" = "ğŸŒ"
"asf" = "ğŸŒ"
"rm" = "ğŸŒ"
"rmvb" = "ğŸŒ"
"flc" = "ğŸŒ"
"avi" = "ğŸŒ"
"fli" = "ğŸŒ"
"flv" = "ğŸŒ"
"gl" = "ğŸŒ"
"dl" = "ğŸŒ"
"xcf" = "ğŸŒ"
"xwd" = "ğŸŒ"
"yuv" = "ğŸŒ"
"cgm" = "ğŸŒ"
"emf" = "ğŸŒ"
"ogv" = "ğŸŒ"
"ogx" = "ğŸŒ"
"aac" = "ğŸµ"
"au" = "ğŸµ"
"flac" = "ğŸµ"
"m4a" = "ğŸµ"
"mid" = "ğŸµ"
"midi" = "ğŸµ"
"mka" = "ğŸµ"
"mp3" = "ğŸµ"
"mpc" = "ğŸµ"
"ogg" = "ğŸµ"
"ra" = "ğŸµ"
"wav" = "ğŸµ"
"oga" = "ğŸµ"
"opus" = "ğŸµ"
"spx" = "ğŸµ"
"xspf" = "ğŸµ"
"mkv" = "ğŸ¬"
"mp4" = "ğŸ¬"
